// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID          uuid.UUID
	CustomerID  uuid.UUID
	Status      string
	Currency    string
	TotalAmount int64
	Items       []byte
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Outbox struct {
	ID            int64
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       []byte
	Headers       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
}

type ProcessedEvent struct {
	Consumer    string
	EventID     string
	ProcessedAt time.Time
}
