// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (id, customer_id, status, currency, total_amount, items, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOrderParams struct {
	ID          uuid.UUID
	CustomerID  uuid.UUID
	Status      string
	Currency    string
	TotalAmount int64
	Items       []byte
	Version     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.ID,
		arg.CustomerID,
		arg.Status,
		arg.Currency,
		arg.TotalAmount,
		arg.Items,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, customer_id, status, currency, total_amount, items, version, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.Items,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersAfter = `-- name: ListOrdersAfter :many
SELECT id, customer_id, status, currency, total_amount, items, version, created_at, updated_at
FROM orders
WHERE customer_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListOrdersAfterParams struct {
	CustomerID      uuid.UUID
	CursorCreatedAt time.Time
	CursorID        uuid.UUID
	PageSize        int32
}

func (q *Queries) ListOrdersAfter(ctx context.Context, arg ListOrdersAfterParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersAfter,
		arg.CustomerID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.Items,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersFirstPage = `-- name: ListOrdersFirstPage :many
SELECT id, customer_id, status, currency, total_amount, items, version, created_at, updated_at
FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListOrdersFirstPageParams struct {
	CustomerID uuid.UUID
	PageSize   int32
}

func (q *Queries) ListOrdersFirstPage(ctx context.Context, arg ListOrdersFirstPageParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersFirstPage, arg.CustomerID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.Items,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execrows
UPDATE orders
SET status = $1, version = version + 1, updated_at = $2
WHERE id = $3 AND version = $4
`

type UpdateOrderStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        uuid.UUID
	Version   int32
}

// Optimistic concurrency: affects 0 rows when another writer bumped the version first.
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
