// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcdb

import (
	"context"
	"time"
)

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, headers, created_at
FROM outbox
WHERE published_at IS NULL
ORDER BY id
LIMIT $1
`

type ClaimOutboxBatchRow struct {
	ID            int64
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       []byte
	Headers       []byte
	CreatedAt     time.Time
}

func (q *Queries) ClaimOutboxBatch(ctx context.Context, batchSize int32) ([]ClaimOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimOutboxBatchRow{}
	for rows.Next() {
		var i ClaimOutboxBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Headers,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimProcessedEvent = `-- name: ClaimProcessedEvent :execrows
INSERT INTO processed_events (consumer, event_id)
VALUES ($1, $2)
ON CONFLICT (consumer, event_id) DO NOTHING
`

type ClaimProcessedEventParams struct {
	Consumer string
	EventID  string
}

func (q *Queries) ClaimProcessedEvent(ctx context.Context, arg ClaimProcessedEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimProcessedEvent, arg.Consumer, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePublishedOutbox = `-- name: DeletePublishedOutbox :execrows
DELETE FROM outbox WHERE published_at IS NOT NULL AND published_at < $1::timestamptz
`

func (q *Queries) DeletePublishedOutbox(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublishedOutbox, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox (aggregate_type, aggregate_id, event_type, payload, headers)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOutboxEventParams struct {
	AggregateType string
	AggregateID   string
	EventType     string
	Payload       []byte
	Headers       []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Headers,
	)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox SET published_at = now() WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, ids)
	return err
}

const tryOutboxLock = `-- name: TryOutboxLock :one
SELECT pg_try_advisory_xact_lock($1::bigint) AS locked
`

// Transaction scoped advisory lock: only one relay replica drains at a time, which keeps events
// strictly ordered. The lock is released automatically on commit or rollback.
func (q *Queries) TryOutboxLock(ctx context.Context, key int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryOutboxLock, key)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
